### ISSUE TITLE
Hero Stats: Crash with command "hs"

### ISSUE THREAD

**Issue by SebRut** [JankGaming/jankbot-modules#1]
TypeError: Cannot call method 'toLowerCase' of undefined
    at Request._callback (/home/sebrut/jankbot/bot_modules/herostats/herostats.js:33:28)
    at Request.self.callback (/home/sebrut/jankbot/node_modules/request/index.js:142:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/home/sebrut/jankbot/node_modules/request/index.js:856:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/home/sebrut/jankbot/node_modules/request/index.js:808:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:883:14
    at process._tickCallback (node.js:415:13)

Checknig if input[1] exists can possibly fix the error

**Comment by twisterghost** [comment]
Fixed in d58a58a2a57a6488d7917fdd03282870a3a108cb
