### ISSUE TITLE
WHOIS: Crash when "whois" input

### ISSUE THREAD

**Issue by SebRut** [JankGaming/jankbot-modules#2]
/home/sebrut/jankbot/bot_modules/whois/whois.js:7
    pattern = pattern.split("").reduce(function(a,b){ return a+".*"+b; });
                                ^
TypeError: Reduce of empty array with no initial value
    at Array.reduce (native)
    at fuzzyMatch (/home/sebrut/jankbot/bot_modules/whois/whois.js:7:33)
    at Object.exports.handle (/home/sebrut/jankbot/bot_modules/whois/whois.js:24:11)
    at SteamClient.bot.on.logger.log.minimap.map.userid (/home/sebrut/jankbot/jankbot.js:174:22)
    at SteamClient.EventEmitter.emit (events.js:106:17)
    at SteamClient.handlers.(anonymous function) (/home/sebrut/jankbot/node_modules/steam/lib/handlers/friends.js:199:8)
    at SteamClient._netMsgReceived (/home/sebrut/jankbot/node_modules/steam/lib/steam_client.js:102:26)
    at SteamClient.handlers.(anonymous function) (/home/sebrut/jankbot/node_modules/steam/lib/steam_client.js:188:10)
    at SteamClient._netMsgReceived (/home/sebrut/jankbot/node_modules/steam/lib/steam_client.js:102:26)
    at Connection.EventEmitter.emit (events.js:95:17)

**Comment by twisterghost** [comment]
Fixed in d35a1252907a8a1bdee4c3ed1659654c2c53dec2

Thanks, keep 'em coming.
